platform :ios, '13.0'

target 'Plant Baby Monitor' do
  use_frameworks!

  pod 'Firebase/Auth'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Database'
  pod 'Charts'
  pod 'TinyConstraints'
  pod 'NVActivityIndicatorView'

end
